# Generated by Django 5.2.5 on 2026-04-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'managed': False, 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={'managed': False, 'verbose_name_plural': 'Reservations'},
        ),
    ]
